services:
    broker:
        image: eclipse-mosquitto
        container_name: broker
        volumes:
            - ./.mqtt/config:/mosquitto/config
            - ./.mqtt/data:/mosquitto/data
            - ./.mqtt/log:/mosquitto/log
        networks:
            - localnet
        ports:
            - '1884:1884'

    node-red:
        build:
            context: .
            dockerfile: ./.node-red/Dockerfile
        container_name: node-red
        depends_on:
            - broker
        volumes:
            - ./.node-red/data:/data/
            - ./.node-red/files:/files/
        user: '0'
        environment:
            - TZ=Europe/Rome
        networks:
            - localnet
        ports:
            - '1880:1880'
        command:
            - npm install node-red-dashboard

networks:
    localnet:
